### ISSUE TITLE
Docs not compiling neither on local neither on docker

### ISSUE THREAD

**Issue by PopBogdan97** [zanna-37/BGP-simulation#18]
- If you try to build the docs locally, it is not guaranteed that the user has ```sphinx-build``` installed.
Error:
```
/bin/sh: line 1: sphinx-build: command not found
make: *** [Makefile:20: docs] Error 127
```
(I cannot understand why the Makefile is using the /bin/sh shell instead of the shell in my environment

- If you try to build the docs on Docker neither the command ```docs``` nor ```build``` are found. Only the command ```clean``` is present (take a look at the Makefile)
Error:
```
Running Sphinx v3.5.3

Sphinx error:
Builder name docs not registered or available through entry point
make: *** [Makefile:20: docs] Error 2
```
```
Running Sphinx v3.5.3

Sphinx error:
Builder name build not registered or available through entry point
make: *** [Makefile:20: build] Error 2
```

**Comment by zanna-37** [comment]
> * If you try to build the docs locally, it is not guaranteed that the user has `sphinx-build` installed.
>   Error:
> 
> ```
> /bin/sh: line 1: sphinx-build: command not found
> make: *** [Makefile:20: docs] Error 127
> ```

We are assuming the user takes care about the dependencies or use Docker. I'm adding that to the documentation.

> (I cannot understand why the Makefile is using the /bin/sh shell instead of the shell in my environment

We are using the official Makefile from read-the-docs, you should probably ask there.

> * If you try to build the docs on Docker neither the command `docs` nor `build` are found. Only the command `clean` is present (take a look at the Makefile)
>   Error:
> 
> ```
> Running Sphinx v3.5.3
> 
> Sphinx error:
> Builder name docs not registered or available through entry point
> make: *** [Makefile:20: docs] Error 2
> ```
> 
> ```
> Running Sphinx v3.5.3
> 
> Sphinx error:
> Builder name build not registered or available through entry point
> make: *** [Makefile:20: build] Error 2
> ```

The command `make docs` was not correct. I'm fixing it. However, it was indicated as optional (the command is inside square brackets `[ ]`). In fact, if you call `docker run` without a command it will default to `make html` which is the correct one.
