### ISSUE TITLE
Bool value saying if a device is an endpoint or not

### ISSUE THREAD

**Issue by PopBogdan97** [zanna-37/BGP-simulation#30]
Since you are already parsing the configuration file, it would be nice to have a bool variable that I can test and which is saying if a device is a router or endpoint (it can be also a Char indicating the type)

**Comment by zanna-37** [comment]
You should use this code to achieve what you want (as written in the `main.cpp`:

```c
if (auto *x = dynamic_cast<Router *>(device)) {
    cout << x->ID << endl;
} else if (auto *x = dynamic_cast<EndPoint *>(device)) {
    cout << x->ID << endl;
}
```
