### ISSUE TITLE
Link status wrong enum 

### ISSUE THREAD

**Issue by PopBogdan97** [zanna-37/BGP-simulation#31]
The link status is stated with an enum, but the correspondent bool is probably wrong.
Behaviour:
```
active -> 0
failed -> 1
```
The other way around could be more intuitive returning true when the link is active

**Comment by zanna-37** [comment]
This is not intended to be used as a boolean value. Other states could be introduced, (e.g. `limited` or `lossy`).
Test it against the enum value, do not assume there is an integer value underneath.
